# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL8iANyzPW2l8XpJB_o4RIGFKKpkbnUU
"""

# Our import statements for this problem
import pandas as pd
import numpy as np
import patsy as pt

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# The code to implement a decision tree
data_train = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")
data_test = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")

##Clean Data
data_train['DateTime'] = pd.to_datetime(data_train['DateTime'])
# Separate into year, month, day, and hour columns
data_train['year'] = data_train['DateTime'].dt.year
data_train['month'] = data_train['DateTime'].dt.month
data_train['day'] = data_train['DateTime'].dt.day
data_train['hour'] = data_train['DateTime'].dt.hour

#Clean Test Data
data_test["DateTime"] = pd.to_datetime(data_test["DateTime"])
data_test["year"] = data_test["DateTime"].dt.year
data_test["month"] = data_test["DateTime"].dt.month
data_test["day"] = data_test["DateTime"].dt.day
data_test["hour"] = data_test["DateTime"].dt.hour

# As usual, Patsy makes data prep easier
y = data_train["meal"]
x = data_train.drop(["meal","id", "DateTime"], axis=1)

model = DecisionTreeClassifier(max_depth=10, min_samples_leaf=50)

#x, xt, y, yt = train_test_split(x, y, test_size=0.2, random_state=42)

modelFit = model.fit(x,y)

# As usual, Patsy makes data prep easier
y = data_test["meal"]
x = data_test.drop(["meal","id", "DateTime"], axis=1)

pred = modelFit.predict(data_test.drop(["meal","id", "DateTime"], axis=1))